import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const privateEnv = createEnv({
  emptyStringAsUndefined: true,
  runtimeEnv: process.env,
  server: {
    // Local sqlite URL in development, managed database URL elsewhere.
    DATABASE_URL: z.string(),
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    // Generated by crabenv copy from .env.example for local development.
    SESSION_SECRET: z.string().min(32),
    SMTP_LOGIN: z.string().optional(),
    SMTP_PASSWORD: z.string().optional(),
    SMTP_FROM: z.string().default("Crabenv Basic <noreply@example.com>"),
  
  
    POKEMON_ENV: z.coerce.number().optional(),
  
  },
});
